# Generated by Django 3.2.5 on 2021-07-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scores',
            name='incorrect',
            field=models.IntegerField(default=0),
        ),
    ]
