# Generated by Django 3.2.5 on 2021-07-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210723_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='unanswered',
            field=models.IntegerField(default=0),
        ),
    ]
