# Generated by Django 3.2.5 on 2021-07-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_scores_unanswered'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='category',
            field=models.CharField(default='All', max_length=50),
            preserve_default=False,
        ),
    ]
