# Generated by Django 3.2.5 on 2021-07-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_scores_stats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scores',
            options={'verbose_name_plural': 'Stats'},
        ),
        migrations.RenameField(
            model_name='scores',
            old_name='stats',
            new_name='q_attempted',
        ),
    ]
