# Generated by Django 3.2.7 on 2021-09-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20210728_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='q_attempted',
            field=models.CharField(default='[]', max_length=65534),
        ),
    ]
